title: Smark Tat
description: Young Ugandan musician, passionate artist, content creator.
author: Icii White
twitter:
  username: smarktat
  card: summary_large_image
social:
  name: Smark Tat
  links:
    - https://twitter.com/smarktat
    - https://github.com/smarktat
logo: https://smarktat.github.io/favicon.png
image: https://smarktat.github.io/og.png
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag