name: Backend Process
on:
  issues:
    types: [opened]
jobs:
  process_comment:
    if: contains(github.event.issue.title, 'COMMENT_ENTRY')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_PERSONAL_TOKEN }}
      - name: Update JSON
        run: |
          COMMENT_JSON='${{ github.event.issue.body }}'
          if [ ! -f comments.json ]; then echo "[]" > comments.json; fi
          jq ". += [$COMMENT_JSON]" comments.json > temp.json && mv temp.json comments.json
      - name: Commit Changes
        run: |
          git config --global user.name "Smark-Backend"
          git config --global user.email "smarktat@github.io"
          git add comments.json
          git commit -m "Update Fan Wall"
          git push
      - name: Close Issue
        run: gh issue close ${{ github.event.issue.number }} --reason "completed"
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}