name: Update Fan Comments
on:
  repository_dispatch:
    types: [new_comment]
jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_PERSONAL_TOKEN }}
      - name: Update comments.json
        run: |
          NAME="${{ github.event.client_payload.name }}"
          PIC="${{ github.event.client_payload.pic }}"
          TEXT="${{ github.event.client_payload.text }}"
          if [ ! -f comments.json ]; then
            echo "[]" > comments.json
          fi
          jq ". += [{\"name\": \"$NAME\", \"pic\": \"$PIC\", \"text\": \"$TEXT\"}]" comments.json > temp.json && mv temp.json comments.json
      - name: Commit and Push
        run: |
          git config --global user.name "Smark-Tat-Bot"
          git config --global user.email "bot@smarktat.com"
          git add comments.json
          git commit -m "New comment from $NAME"
          git push